### ISSUE TITLE
Use HttpClient instead of HttpWebRequest

### ISSUE THREAD

**Issue by vanillajonathan** [FortnoxAB/csharp-api-sdk#100]
Use the modern [`HttpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) instead of the old dirty [`HttpWebRequest`](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest).

**Comment by richardrandak** [comment]
Are there some benefits for the SDK end-users?

I actually tried to rewrite it by using HttpClient but I have come across the issue with uploading a file containing öäå characters in its filename. The HttpClient does not allow to use them. When set header string value manually, it crash with Exception "Request headers must contain only ASCII characters". When set as argument in Content.Add method, the filename is converted from by  `fileåöä.txt` to `__utf-8_B_ZmlsZcOlw7bDpC50eHQ___`. Unfortunetelly the server (Fortnox) does not decode it back, but use it directly for the entity name. 

If you know some workaround, let me know. Otherwise, I will continue using HttpWebRequest where the headers content char-set is not enforced.

**Comment by vanillajonathan** [comment]
If you were to allow the `HttpClient` to be passed into the constructor it could be retrieved from a pool using [`HttpClientFactory`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1) which could improve scalability.

Perhaps the file name needs to be encoded?

There is the [WebUtility.UrlEncode](https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.urlencode?view=netcore-3.1) method and the [Uri.EscapeUriString](https://docs.microsoft.com/en-us/dotnet/api/system.uri.escapeuristring?view=netcore-3.1) method.

```cs
WebUtility.UrlEncode("Räksmörgås"); // R%C3%A4ksm%C3%B6rg%C3%A5s
Uri.EscapeUriString("Räksmörgås")); // R%C3%A4ksm%C3%B6rg%C3%A5s
```

**Comment by richardrandak** [comment]
The encoding did not solve the issue. The file entity will end up with corrupted name.
I will contact Fortnox backend developers to see what can be done.

**Comment by vanillajonathan** [comment]
Perhaps something like this:

```cs
var file = new StreamContent(stream);
file.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
var content = new MultipartFormDataContent();
content.Add(file, "file_path", fileName);
var response = await _client.PostAsync("api/Foo/", content);
```
