### ISSUE TITLE
Different Token in InvoicePaymentConnector in Multi-tenant web application

### ISSUE THREAD

**Issue by developeerr** [FortnoxAB/csharp-api-sdk#110]
I am using this library in our multi-tenant web application to communicate with the Fortnox API. In the system, on a scheduler basis, we book payments against invoices and this runs partially on each tenant.

The MakePayment method is implemented as follows to create and book a payment.

```
public class FortnoxBookkeep
{
    public FortnoxBookkeep(string clientSecret, string token)
        {
            if (string.IsNullOrWhiteSpace(token))
                throw new Exception("Empty Token");

            ConnectionCredentials.ClientSecret = clientSecret;
            ConnectionCredentials.AccessToken = token;

            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
        }

       //First create the payment record and do some additional processing in our system
      //Secondly book the created payment
       public CreatePaymentResponse MakePayment(BookkeepPaymentRecord paymentRecordInfo)
       {
            var response = new CreatePaymentResponse();
            if (paymentRecordInfo.PaidAmount > 0)
            {
                invoicePaymentConnector = new InvoicePaymentConnector(); 

                //Add Main Payment Record
                fortnoxPaymentRecord = new InvoicePayment()
                {
                    InvoiceNumber = paymentRecordInfo.InvoiceDocumentNumber,
                    PaymentDate = paymentRecordInfo.PaidDate.ToFortnoxDateFormat(),
                    ModeOfPayment = paymentRecordInfo.ModeOfPayment,
                    Amount = paymentRecordInfo.PaidAmount.ToString(CultureInfo.InvariantCulture)
                };

                //Create fortnox payment record
                var accessToken = invoicePaymentConnector.AccessToken;
                fortnoxPaymentRecord = invoicePaymentConnector.Create(fortnoxPaymentRecord);

                if (invoicePaymentConnector.HasError)
                {
                    //Handle Error
                    return response;
                }

                response.GeneralPaymentNumber = fortnoxPaymentRecord.Number;
                
                //Execute some additional functionality (not time-consuming)
                //Remove it since it not necessary here

               //Booking the Payment
               invoicePaymentConnector.Bookkeep(fortnoxPaymentRecord.Number);

                if (invoicePaymentConnector.HasError)
                {
                   //Handle Error
                    return response;
                }
            }

            return response ;
       }
}
```

The issue is as follows -

The payment is correctly created against the correct access token.
Most of the time, the payment book without any issues.
But on some occasions, when the system tries to book the created payment, it books against a different access token (token from another tenant). This is verified by Fortnox Support.

What could be the reason? 
Also, I noticed that on the Wiki it says that not to use "ConnectionCredentials.ClientSecret" in a web application as I used in the constructor. Could that be a reason for this?

Thanks.

**Comment by richardrandak** [comment]
Hello!
Which version are you using?

The implementation until today was (v3.4.0), that if the connector has no access-token or client-secret defined, it uses the credentials defined by the static class. It "consumes" the credentials on every request. So, if you changed the static credentials, it also affects the old connectors.
This may have caused the wrong tenant usage, especially with async requests, since the request (and credentials) from old connector could be delayed and sent AFTER you changed the static credentials to new tenant, even though in code it may look that you changed them before sending the request.
That is my only explanation right now. When using multiple credentials, I would rather use the connector's properties to be sure the correct credentials are used.

Today I made a release, where the static credentials are "consumed" by connector in constructor. Therefore, changes to static credentials will not affect already existing connectors. This may fix your problem without any code modification.

Please let me know more details if the issue persists.

**Comment by developeerr** [comment]
Hi, 

I am using V3.0.0. 
I am just wondering since I create a new object for every payment request, how could it be changed to a token from another tenant. (Sorry, I do not have any idea about how this internally works in the library)

 `foreach every payment
      var bookKeepFactory= new FortnoxBookkeep();
      var response = bookKeepFactory.MakePayment(bookkeepPaymentRecord)
`

Also, every payment record has created successfully against the correct token. (Still, we have not found any payment records that created against incorrect token). Only a few occations, when the system tries to book a created payment, it failed because it tries against an incorrect token.

I would really appreciate it If you could explain this further.
Also, I will update the library to V3.4.0.

Thanks.

**Comment by richardrandak** [comment]
As I said, you create an object, but internally it uses the static credentials, which is changed later to a new tenant.
I assume, this code is called asynchronously from somewhere. So the last request (bookkeep) could be in rare cases executed after credentials are changed. It is my theory, because I don't see any other explanation from your code snippet, but who knows if that is the case.

Also, version 3.0.0 is quite old, and it was done before I took over this project. I have rewritten a lot of things so maybe there was some other problem in v3.0.0 which is causing this.

Please update to 3.4.0 if possible

**Comment by developeerr** [comment]
Thank you for the explanation and I hope this could be a rare case. :) 
Yes, I will update to V3.4.0 and update this thread afterword. 

Thanks.

**Comment by richardrandak** [comment]
Let me know in case of troubles with updating to the version.

**Comment by developeerr** [comment]
Hi,

I updated the version to V3.4.0. I tried to create a payment record without modifying the program. It works in my local environment but it does not work on the QA server. I feel like the program breaks when I try to communicate with the API. 
The problem is that I'm not getting any error or exception even. 

I am using the static variables to define the token and client secret. 
I thought of changing it to instance variables and try. I will let you know the result. 

If you have any thoughts on this. Please do share. 
Thanks.

**Comment by richardrandak** [comment]
Yes, Fortnox server requires at least TLS v1.2, but I don't think that is the issue here.. you would get an exception. What OS version is installed on the server? You can set the TLS version explicitly by `System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` and check if that helps.

If the program is stuck, it can be something with threads / synchronization. There was an issue #94 before, but it was fixed. Can you write all methods of connectors you are calling?

**Comment by richardrandak** [comment]
Sorry, now I see you haven't modified the program. Is your code example the only interaction with Fortnox?
I can check if the #94 could be the issue here. I can check it later today.

**Comment by developeerr** [comment]
Since anything didn't work I modified the program and I remove the static variables and used instance variables to define access token and client secret. But sill I'm getting the same issue. 

```
async task<bool> makepayment(parameters goes here)
{
  //execute some database operations
  
  await this._bookkeepService.MakeBookkeepPayment(param1, param2, param3);
}

async task<bool> makebookkeeppayment(param1, param2, param3)
{
     //database query with await
    var fortnoxAPISettings = await this._apiSettingsService.GetAPISettings(Common.Enum.APIServicesEnum.Fortnox);
    var clientSecret = fortnoxAPISettings.SandboxTokenConsumerKey;
    var accessToken = fortnoxAPISettings.SandboxToken;
    
    //Calling the library using the following connectors
    var invoiceConnector = InvoicePaymentConnector (ClientSecret = clientSecret, AccessToken = accessToken);
   //using the invoicePaymentConnector send the create the main payment in fortnox

    var voucherConnector = new VoucherConnector() { ClientSecret = this.ClientSecret, AccessToken = this.AccessToken };
   //overpaid or otherfees create as vouchers in Fortnox using the VoucherConnector

  //If everything works fine
  //booking the created main payment.
}
```

I hope this information would be enough to track the issue.
If you need any additional information, please let me know.

**Comment by richardrandak** [comment]
I have no idea.. can you try to call just a simple `var result = new CompanySettingsConnector().Get()` on the QA server? 
If not, try to call `var result = CompanySettingsConnector().GetAsync().ConfigureAwait(false).Result`
If not, try to call `var result = await CompanySettingsConnector().GetAsync()`

**Comment by richardrandak** [comment]
Hi! Was the issue resolved after all?
