### ISSUE TITLE
AbsenceTransactionConnector - missing AbsenceTransactionSubset?

### ISSUE THREAD

**Issue by ingemarcarlo** [FortnoxAB/csharp-api-sdk#114]
AbsenceTransactionSubset seems to be missing...

Or can I really read/Find all Absence transactions from an EntityCollection of AbsenceTransaction? To me this seems like a bug, or I am missing something?

public EntityCollection<AbsenceTransaction> Find()
		{
			return FindAsync().Result;
		}

**Comment by dennisahlin** [comment]
According to API documentation, the entities are the same for single get and list (some other entities have this as well).
https://developer.fortnox.se/documentation/resources/absence-transactions/

I assume due to the entity being so small (few properties), the complexity of having an extra sub entity doesn't outweigh the miniscule performance gain.

**Comment by richardrandak** [comment]
As Dennis says, the entity is the same, so no subset entity is needed.
