### ISSUE TITLE
HttpClient issues

### ISSUE THREAD

**Issue by Sharparam** [FortnoxAB/csharp-api-sdk#116]
Each connector seems to `new` up its own `HttpClient` for use within the connector, this doesn't seem in line with [Microsoft's recommendations regarding making HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core).

If going the `HttpClient` route, there should be an application-level static client used for all requests as needed.

Furthermore, there should be constructors for the connectors that take a user-supplied `HttpClient`, so that we can hook them up with properly pooled `HttpClient`s when available (such as in an ASP.NET Core app, which is our usecase, where we have access to `IHttpClientFactory`).

**Comment by richardrandak** [comment]
Hello ad thanks for the feedback! 
Using new httpclient in each connector should not cause too much trouble, if user don't create new connector for each request. I am not sure, however, how much trouble it is in ASP.NET.
I wanted to make a single HttpClient before, but I came across few issues with current SDK design which made it harder. I still plan to make HttpClient inject-able. At least by a property for now.
Feel free to write more suggestion or even contribute.

**Comment by Sharparam** [comment]
I was thinking of adding constructors to the connectors so that a custom `HttpClient` can be provided. This shouldn't affect current functionality as the default would be to behave as it already does.

Would that be a welcome contribution?

**Comment by richardrandak** [comment]
I was thinking about that. 
The Timeout property of a connector will have to be removed in this case. 
It is leftover from before when WebRequest was used. Since Timeout can not be set for each request, but instead HttpClient has to be modified, changing it will affect all the connectors which use the same HttpClient.

Moreover, because of some server side issues, the file upload request can't use HttpClient but is using WebRequest.
Right now it was nicely hidden, but making HttpClient injectable will make this inconsistent.

**Comment by Sharparam** [comment]
Hm, it might need some deeper work. One issue seems to be that connectors are not thread-safe, each new request requires a new connector to be constructed (that usecase however should benefit from having the HttpClient instances be generated by the factory).
