### ISSUE TITLE
Unable to get AccessToken using AuthorizationConnector

### ISSUE THREAD

**Issue by PatrickFermont** [FortnoxAB/csharp-api-sdk#120]
When trying to get AccessToken using the AuthorizationConnector I always get back 403.
Inspecting the headers I see that behinds client-secret a "comma and space" is added.

```
AuthorizationConnector authorizationConnector = new AuthorizationConnector();
return authorizationConnector.GetAccessToken(authorizationCode, "AB1234"); 
```
When I do the same in Postman (so without "comma and space") I get the AccessToken.

Do I miss something?

**Comment by PatrickFermont** [comment]
Using NuGet package Version 2.1.6 works fine so it must be somewhere between 2.1.6 and latest version.

**Comment by richardrandak** [comment]
It is a bug, I'll fix it

**Comment by richardrandak** [comment]
I released the fix. 
Problem was that the credentials (client secret and access token) were put to headers by the BaseClient, which is inherited by all connectors. 
In case of AuthorizationConnector, the credentials are not yet known and should not be used. By adding them, the undefined/empty client secret was put second time (that's why the comma appeared)

**Comment by PatrickFermont** [comment]
Solved. Thank you.
