### ISSUE TITLE
Add account in specific financial year

### ISSUE THREAD

**Issue by LarsLautrup** [FortnoxAB/csharp-api-sdk#123]
Hi.
How do you create an account in a specific financial year?
The API documentation specifies that, "To create an account to a specific financial year it needs to be added in the POST URL."

How do I do that using the SDK?

Regards,

Lars.

**Comment by richardrandak** [comment]
Good question.. the FinancialYearID property of connector (and after refactoring, the property of AccountSearch) was meant for Find method. The url parameter will not be added in case of Create method. This maybe worked long time ago.
This is an issue and I can fix it by adding a parameter to the create method to inject the financial year. Would that work for you? Which version are you using?

If you know of more similar cases like this, when an additional parameters are needed for Create/Update/Delete method, let me know

**Comment by LarsLautrup** [comment]
Hi...
That would be perfect! :-)
I'm currently rewriting a very old integration to Fortnox and has updated the SDK to version 3.5.1.
I have not yet discovered any similar cases, but I'll make sure to let you know, if I do

Thanks!

/Lars.

**Comment by richardrandak** [comment]
It seems like financial year in URL must be used also in Get/Update/Delete to work with account outside of default year.
The design in v3.5.1 is not flexible for adding parameters so injecting them is not thread-safe. To be safe, use new connector in each thread. Anyway, update to v3.5.3 NuGet for the fix.

Since you are rewriting already, consider trying the beta version (4.0.0-beta). There is little more changes to which you need to adapt your code, but should be better for future. I changed the connector design there to not keep any request-specific data (like search parameters or error information)
I will add the fix there soon too.

I also realized, similar problem is with vouchers. They are similarly dependent on financial year, but the SDK has only parameter available on Get method.
Thank you for reporting the issue.

**Comment by LarsLautrup** [comment]
Thanks a lot, Richard!!
I'll check out the beta version. Have you any idea, when the beta will replace the 3.5.x version? 
I need to have my implementation up and running in production in start january, so the version, that I'm going to use, should be somewhat stable  ... ;-)

/Lars.

**Comment by richardrandak** [comment]
I believe the beta is stable, at least compared to the v3.5.* versions. But I have not got any project to use it in, for now. To be honest, there is no official acceptance/testing procedure on this SDK. I am the only active maintainer.
If you have any issues let me know.
Here, your issue is fixed in 
v3.5.3 => https://www.nuget.org/packages/Fortnox.NET.SDK/3.5.3
v4.0.1-beta => https://www.nuget.org/packages/Fortnox.NET.SDK/4.0.1-beta

**Comment by LarsLautrup** [comment]
Thanks again, Richard! 👍 🥇 
I'll upgrade the project to the beta and let you know if something doesn't work right. I'll do a lot of testing before the new integration goes into production, but I can't promise that I'll be testing all of the functions in the entire SDK :-)

/Lars.

**Comment by richardrandak** [comment]
Perfect! :)
