### ISSUE TITLE
Getting file from Archive

### ISSUE THREAD

**Issue by martenw** [FortnoxAB/csharp-api-sdk#128]
Is it possible to get file info from archive? Not download the byte-array but getting the info.

Seems method is available (https://developer.fortnox.se/documentation/resources/archive/#GET) but from what I can see the .net api only supports getting folders

Regards,
Mårten

**Comment by richardrandak** [comment]
Hello!
From the "GET" documentation: `If your path or Id points to a file, the content will be a returned as a filestream.` So, I think there is no way to obtain the single file info.

**Comment by martenw** [comment]
Ah, I can see that now also, that is unfortunate.

My scenario is that I just need to list files connected to an article, is there any way I can get that info (would be perfect if filename was available in `ArticleFileConnection`)?

**Comment by richardrandak** [comment]
I can ask the Fortnox support if there is a way to fulfill that, but I am afraid there is not (through the public API). It is strange, since the "file info" entity is clearly visible in the folder structure so it is logical to expect it to be retrievable.

Filename is neither available in `InvoiceFileConnections ` for instance.

**Comment by martenw** [comment]
Since the entity is there I agree that it seems to be something missing in the base API.
