### ISSUE TITLE
Order.StockPointCode

### ISSUE THREAD

**Issue by brujah** [FortnoxAB/csharp-api-sdk#131]
Hi,

I am not able to find the Order.StockPointCode when looking through code, is it not available within the SDK?

**Comment by richardrandak** [comment]
Hello!
It is not. I assume it was added as part of the Warehouse API module, which was not incorporated to the SDK.
Moreover, I don't see the property `StockPointCode` in the orders [documentation](https://developer.fortnox.se/documentation/resources/orders/)

**Comment by brujah** [comment]
Hi,

It is in the return data when calling a specific order but it does not seem to be in their documentation though.
If you look at https://developer.fortnox.se/blog/new-attributes-and-action-on-orderinvoicesupplier-invoice-endpoint/ it is mentioned.

Anything that can be added?

**Comment by richardrandak** [comment]
I see, you are right, it is in the response.
I am sorry though, but in this point I don't plan to add the Warehouse-related properties or endpoints, especially, since the documentation does not seem to be consistent.

Fortnox does not maintain the SDK anymore. 
Since I don't have any project working with the warehouse module, it is not efficient for me to spend time on implementing it.
You are free to fork the repository or contribute to it :)

**Comment by richardrandak** [comment]
A generic issue/task #133 was created for warehouse. I am closing this one
