### ISSUE TITLE
Unable to set label on invoice

### ISSUE THREAD

**Issue by thelalle** [FortnoxAB/csharp-api-sdk#138]
In previous versions we´re able to set invoice labels by:
invoice.Labels.Add(new Label {Id = "2"});

But now we need to either use reflection to set the Id property, or fetch it from the api LabelConnector first.
It would be nice to be able to do:
invoice.Labels.Add(new Label(2));

**Comment by richardrandak** [comment]
I agree, that would be nice, but the Id of a label is read-only for a valid reason. When using Labels endpoint, the Id can not be specified in requests. This is a common feature for other endpoints.
For invoices, however, the "labels" seems like just references, similar to customer number, but for some reason the API designer made it a "complex object" containing the Id instead of just an integer. In the beginning, I just merged it with the full Label entity, but now it seems it is not right and it should be two different.

Conclusion - I could make a new entity LabelReference with public Id setter
It would then be `invoices.Labels.Add(new LabelReference(2));`

If you want to add labels which you had retrieved, you would have to convert it. Something like
```
var labels = labelConnector.Find().Entities;
invoice.Labels = labels.Select(x => new LabelReference(x.Id))
```

What do you think?

**Comment by thelalle** [comment]
I think it sound great.

Just a question thou (and I did not check), the invoice.Labels[0].Descriptor == null in the current solution?

**Comment by richardrandak** [comment]
Honestly, I haven't tried either
But from documentation examples it is just the Id without description also in invoice responses.

I will check it, but if you can also double check I will be grateful. Sometimes the account settings can make a difference in what you're getting.

**Comment by richardrandak** [comment]
It seems the server actually refuses the invoice if it has label with description defined. It must have just the Id. So, the LabelReference type was definitely needed.

I have uploaded a new Nuget (preview) which you can check. It should now be possible to create invoice with labels and also filter invoices by a label. Please let me know if it works for you.
https://www.nuget.org/packages/Fortnox.NET.SDK/4.0.4-preview

**Comment by thelalle** [comment]
Tested and it works great!
