### ISSUE TITLE
TermsOfDeliveryConnector

### ISSUE THREAD

**Issue by LennyHoglund** [FortnoxAB/csharp-api-sdk#141]
The TermsOfDeliveryConnector do not contain information regarding CurrentPage, TotalPages and TotalResources. This is a minor issue. However, if a procedure loops thru all "Simple tables" then the above information is needed. 

[Document 31.pdf](https://github.com/FortnoxAB/csharp-api-sdk/files/6122144/Document.31.pdf)

**Comment by richardrandak** [comment]
The problem is that the API response itself, does not have the information. I also checked with Postman, it is really not included. 
https://developer.fortnox.se/documentation/resources/terms-of-deliveries/

This seems to be a problem for multiple endpoints. for instance Labels. I assume, no paging is needed and all entities are send in every response.
What I could do, is calculate it inside the SDK to keep it consistent with others. However, i am not sure if it is right to pretend the metadata are present, while in reality, they are not.

What do you think?

**Comment by richardrandak** [comment]
It also seems that the "paging" parameters, like **limit** or **offset** are also ignored for these endpoints

**Comment by LennyHoglund** [comment]
Hello Richard,

Yes, no paging is needed for some entities, but it is convenient to use the same code for most of the tables. I think we should leave it as it is. We have to implement a work-around for the connections missing this information. Maybe someday this information will be included  for all tables.

Thank you very much for your quick response,
Lennart

***@***.***D71675.EB5945C0]
Lennart Hoglund
CEO & Senior System Architect

Lewab AB
Nytorgsgatan 24
116 22  Stockholm
Sweden
Phone    +46 (0) 8 641 3911
Mobile   +46 (0)70 646 1328
E-mail     ***@***.******@***.***>
Site          www.lewab.com
