### ISSUE TITLE
Revoke refresh token

### ISSUE THREAD

**Issue by martenw** [FortnoxAB/csharp-api-sdk#224]
https://developer.fortnox.se/general/revoke-access-token/

Is revoke supported using this package?

**Comment by richardrandak** [comment]
Not at the moment. I'll add it.

**Comment by martenw** [comment]
Great, thank you!

**Comment by richardrandak** [comment]
I have created a preview NuGet - https://www.nuget.org/packages/Fortnox.NET.SDK/4.2.9-rc

I have added the two revocation methods to the StandardAuthWorkflow.. I noticed it gives me success even for made-up tokens.

I tested revocation of refresh token, it works -> the revoked refresh token becomes invalid.
I could not test revocation of legacy tokens, since I don't have any I could revoke.. the ones I have I need :)

Please let me know if it works for you.

**Comment by richardrandak** [comment]
I wonder if it is actually possible to have a OK response with "not revoked" body.
E.g.
```json
{
  "revoked": false
}
```

**Comment by martenw** [comment]
I have not tested the direct api call myself, not clear from documentation what the api returns on invalid token or revoke failed.

**Comment by richardrandak** [comment]
Speaking to support, it should indicate if the token was invalidated (true) or was already invalid (false). However, in reality, i am always getting "true", even if the token is made-up.

**Comment by martenw** [comment]
Ok, thank you for the update.

Sorry for not getting back on testing, have not had time to implement and test the new feature yet. 
Will post an update here when done.
