### ISSUE TITLE
GLN and GLNDelivery missing on the Customer

### ISSUE THREAD

**Issue by ToniMontana** [FortnoxAB/csharp-api-sdk#32]
This blog post describes that GLN and GLNDelivery is available on the Customer resource:
https://developer.fortnox.se/blog/gln-in-the-customer-resource/

However it is missing in the csharp-api-sdk.

**Comment by xeterixon** [comment]
From what I can tell, it's not available in the public API. At least it's not described in the documentation.

However, using the RESTful API, you do get the info.
It's even possible to change it by PUT-ting ```{"Customer": {"GLN": "SOMENUMBER"}}``` to a Customer.

It should not be that difficult to add it the the C# Customer model, though. I have added other missing stuff to my fork of this repo.

Also, from what I can tell, it's pretty "silent" here, so don't expect things to be fixed in a jiffy... Fork it and fix it, seems to be the melody...
