### ISSUE TITLE
Properties and types

### ISSUE THREAD

**Issue by vforteli** [FortnoxAB/csharp-api-sdk#38]
I noticed that all properties are created as strings. For some fields this is not a problem, but for example when creating an order and setting the Price property, the API responds with an error that the type must be a float. I changed this manually in https://github.com/FortnoxAB/csharp-api-sdk/blob/master/FortnoxAPILibrary/Entities/Order.cs and it works fine, but shouldnt all properties be typed according to eg https://developer.fortnox.se/documentation/resources/orders/ ?

**Comment by davidulvmoen** [comment]
Thank you for your information! 

This is a well known limitation, however due to initial implementation it is hard to change. First and foremost it would break backwards compability that we do not want. It would also "out of the box" be a subject for leaky CRUD etc.

However I totally agree with you, and in the long run it will probably happen. Right now, I am instead planning to fix this with something like extension method for next release, were you can easialy map between our types.
