### ISSUE TITLE
Remove call to appdomain-wide setting of allowed TLS protocols

### ISSUE THREAD

**Issue by anderssonjohan** [FortnoxAB/csharp-api-sdk#78]
https://github.com/FortnoxAB/csharp-api-sdk/commit/061a8c5a065ad4edda5462e614f37356ebc88fb3

This makes the whole application vulnerable where the library is used as it will change the allowed security protocols not only for this library but for the whole application.

If a user of the library needs to change the settings of ServicePointManager it can do so in their app. Libraries should not change this global object.

This is known best practices and this should be treated as a security vulnerability in the library.

Best practices:
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

> We recommend that you:
> * Do not specify the TLS version. Configure your code to let the OS decide on the TLS version.
> * Perform a thorough code audit to verify you're not specifying a TLS or SSL version.

It's also really bad that this wasn't mentioned in the release notes here:
https://github.com/FortnoxAB/csharp-api-sdk/releases/tag/3.1.0

I would want to ask you to reveret the commit above and withdraw the 3.1.0 release before releasing this to nuget (where it will get a much larger spread than here on Github).

**Comment by richardrandak** [comment]
I agree with you the best practices is to not have hard-coded TLS version. And it is not hard-coded.
By default, the version is taken from ServicePointManager, so there is no change. 
Basically, the whole feature is that library provides a setter which sets the version in service point manager without accessing that object directly. Yes, kind of useless, since you can change it yourself directly, but its nicer to have everything together.

The real issue I see is that it really change the settings globally, which can be an unexpected for some programmers. So, I will revert the commit and rather write a section how to change the protocol to the wiki page.
