### ISSUE TITLE
ArchiveConnector and GetFolder

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#86]
In the previous version i could get a Folder by calling ArchiveConnector.Find(RootFolder.Inbox_SupplierInvoices)
How does it work in the new version ? How do i get the folder Inbox_SupplierInvoices ?
GetRoot doesn't work !

**Comment by richardrandak** [comment]
hmm.. ideally ArchiveConnector.Find("inbox/inbox_s") or
InboxConnector.Find("inbox_s") should work but seems it does not.

Seems that the the documentation is wrong
https://api.fortnox.se/3/inbox/inbox_s -> this works
https://api.fortnox.se/3/inbox?path=inbox_s -> does not work (returns the root, parameter is ignored)

Seems like I just have to put the folder name as URL part instead of parameter.
I will fix this and your other issue with UTF8 chars, and make a new release in next days, latest on Monday. Is that alright?

**Comment by bpaolo71** [comment]
It sounds great!

**Comment by bpaolo71** [comment]
Please check all methods in ArchiveConnector.
GetRoot doesn't work
UploadFile(filepath, "inbox_s") doesn't work

**Comment by richardrandak** [comment]
Yes, all of those has the same problem I think.
But, UploadFile works for me with using Inbox connector, you can try that meanwhile.

In tests I am using
`var tmpFile = new InboxConnector().UploadFile("tmpImage.png", Resource.fortnox_image, "inbox_s");`

**Comment by richardrandak** [comment]
I made a hot-fix release which should solve your issues. Can you please try it and let me know if that worked for you?

To get the folder use:
`archiveConnector.GetFolder(StaticFolders.SupplierInvoices);`
To upload a file
`archiveConnector.UploadFile(fileName, fileData, StaticFolders.SupplierInvoices);` or
`archiveConnector.UploadFile(localPath, StaticFolders.SupplierInvoices);`

**Comment by bpaolo71** [comment]
Now it's working fine :)
