### ISSUE TITLE
DocumentNumber missing when order is created

### ISSUE THREAD

**Issue by magmo-work** [FortnoxAB/csharp-api-sdk#91]
When I create a order using "orderConnector.Create(newOrder);" and then try to retrieve the generated order id using this newOrder.DocumentNumber, its allways null. Shouldnt that order id be available?

**Comment by richardrandak** [comment]
Thanks for reporting the issue. What version do you use?

**Comment by magmo-work** [comment]
I just downloaded it last week, version 3.1.1.0

**Comment by magmo-work** [comment]
I can get it from orderConnector.ResponseContent Json but it seems like it should be available like I described above.

**Comment by richardrandak** [comment]
Yes, the document number property should be populated. I will look into it. 
Since you started just recently, if you can, please use the last version from beta branch (3.2.3-beta). 
I checked the creating an order with that version and it works fine. Many issues were solved there and I will replace the main branch soon.

**Comment by magmo-work** [comment]
If I try the Beta (3.2.3) I get these errors when connecting...

'orderConnector.AccessToken' threw an exception of type 'System.TypeInitializationException'
'orderConnector.BaseUrl' threw an exception of type 'System.TypeInitializationException'
'orderConnector.ClientSecret' threw an exception of type 'System.TypeInitializationException'

using this code..
            var orderConnector = new OrderConnector
            {
                AccessToken = "xxxx", ClientSecret = "xxxx"
            };


And If I change back to the previous master version 3.1.1.0 it works fine?

**Comment by richardrandak** [comment]
That exception seems weird. Like the whole class can't be loaded. Probably some incompatibility.
What .NET version does your project use?

**Comment by magmo-work** [comment]
4.8

**Comment by richardrandak** [comment]
Then it should work. I've never seen this exception. Do you have the other dependencies referenced like Newtonsoft.JSON?  Or you can try using the SDK as [NuGet](https://www.nuget.org/packages/Fortnox.NET.SDK/3.2.3-beta) package. If imported from VisualStudio, check the "Include pre-release" so it shows you the latest version.

Otherwise, you can send me your solution and I will take a look what is wrong.

**Comment by richardrandak** [comment]
I think the error is due to connnector's static property using third party RateLimiter. Since you don't have a reference in your app domain, every usage of the class will fail. This library was not used in 3.1.1 so that would explains the different behavior.

I would recommend to use the Fortnox SDK NuGet directly, so all the dependencies are included automatically.

**Comment by magmo-work** [comment]
Yes, if I add reference to RateLimiter or use the NuGet directly it works as it should, but the DocumentNumber is not available in the Beta release either.

**Comment by richardrandak** [comment]
Alright, you have to assign the result into your variable.
`newOrder = connector.Create(newOrder);  `  Are you doing that or are you trying to get `DocumentNumber` from your "original draft"? The method does not modify your variable.

**Comment by magmo-work** [comment]
Allright, yes I did try to retreive the id from the "original draft", I thought it was updated, but when changing it works fine. Thanks! You mentioned that this beta release will soon be released as master. Any timeline for that yet?

**Comment by richardrandak** [comment]
You are welcome, thanks for the questions.
I was thinking about merging it right now actually, to reduce the confusion for new users :)

**Comment by magmo-work** [comment]
That would be awsome :)
