### ISSUE TITLE
Problems with customerConnector.Find() in ASP.NET

### ISSUE THREAD

**Issue by Pillzan** [FortnoxAB/csharp-api-sdk#94]
Hi! 

I´m trying to integrate Fortnox with a ASP.NET solution for a customer but I´m having trouble using some of the features and it´s a very strange problem.

I made a simple standard ASP.NET WebApplication in visual studio, framework 4.7.2 and put this code in the controller just for a quick test.

```
ConnectionCredentials.AccessToken = "xxx"; // valid token
ConnectionCredentials.ClientSecret = "xxxx"; // valid secret

var customerConnector = new CustomerConnector();
customerConnector.Name = $"John Doe"; // valid user
var foundCustomer = customerConnector.Find();
```

But the Find(); (Get() doesnt work either) never finishes, it just keeps going forever and ever, no exception, no nothing.
I can still create/delete/update customers with the customerConnector, but not Find()/Get();

When i use the exact same code in an Console application (same framework version), the code works every time and i get the correct data.

I use the latest stable Fortnox.NET.SDK version (3.3.0)

**Comment by richardrandak** [comment]
That is very strange issue. I am not very familiar with ASP.NET, but it still should work. 
Did you try other connectors?
Do you use the SDK as NuGet package?

**Comment by dpse** [comment]
I'm trying out the API and have the same issue in WinForms.
Just tested the article and customer connectors and Find() never returns.
The asynchronous methods work just fine however.

**Comment by dpse** [comment]
Hello! Took a look at the code and this seems to be a deadlock caused by the SynchronizationContext being captured and the synchronous methods just calling .Result, which is blocking. In a console app this works fine since there is no context being captured but in e.g. WinForms there is a deadlock since the Task tries to post back to the main thread which is already blocked, causing a deadlock. Adding ConfigureAwait(false) to all awaits should probably resolve this. I can test and submit a pull request if you want.

**Comment by richardrandak** [comment]
Yeah, I read about the ConfigureAwait(false) just now, and seems that could fix the issues. 
You are welcome to submit a pull request. :)
