### ISSUE TITLE
Cancelled property on supplier invioces not parsed correctly

### ISSUE THREAD

**Issue by figursagsmats** [FortnoxAB/csharp-api-sdk#96]
Seems like the property Cancelled of SupplierInvoice and SupplierInvoiceSubset is always null even if the API returns true or false. Looks to med like the json property name is actually "cancel" rather than "cancelled".

**Comment by richardrandak** [comment]
You are right, it is wrong in documentation as well.
I will fix it for the next release. Please let me know if you find other issues.

**Comment by richardrandak** [comment]
So, actually, the JSON for SupplierInvoice has property "**Cancelled**" while the JSON for SupplierInvoiceSubset has "**Cancel**". For some reason I mapped it the other way around. 

Now it is fixed in master branch. I will do release with NuGet next week, since I created a new release just yesterday.
