### ISSUE TITLE
ArchiveConnector not downloading file

### ISSUE THREAD

**Issue by figursagsmats** [FortnoxAB/csharp-api-sdk#99]
I've found that in my case, when trying to download an existing invoice file from the archive DownloadFileAsynx() returns null:
```
var connector = new ArchiveConnector();
connector.ClientSecret = _fortnoxClientSecret;
connector.AccessToken = _fortnoxAccessToken;
var bytes = await connector.DownloadFileAsync(fileId); //returns null
```
But making the request by myself (with flurl) works fine:
```
var bytes = await "https://api.fortnox.se/3/"
   .AppendPathSegment("archive")
   .SetQueryParam("fileid", fileId)
   .WithHeader("Client-Secret", _fortnoxClientSecret)
   .WithHeader("Access-Token", _fortnoxAccessToken)
   .WithHeader("Accept", "*/*")
   .GetBytesAsync();
```
Am I missing something here or is this a bug?

**Comment by richardrandak** [comment]
Can you check the `connector.Error` property?

From the example you provided, there is one difference. "FileId" should be entered as part of the URL path, but your working code enters it as query parameter. It is strange, because according to the documentation there is only "path" but not "fileid" parameter, but maybe it accepts it anyway. 
Therefore, I think you are using file path instead of file id value. Can you tell me the value of it? File Id should be in GUID format e.g. "ecf2a0e7-06b3-4067-9614-f5da77f0e008"

**Comment by figursagsmats** [comment]
I will check the error as soon as possible. 
I've noticed that the documentation is ambiguous when it comes to fetching files from archive. [Invoice File Connetions](https://developer.fortnox.se/documentation/resources/invoice-file-connections/) suggests fileid should be passed as a parameter. But [Archive](https://developer.fortnox.se/documentation/resources/archive/) docs states it should be passed as part of the path.

**Comment by richardrandak** [comment]
I did some investigation, and the documentation is very confusing.
Seems that there is difference between "Id" and "FileId" in Archive. You can get the file by "Id" (entered as url part) as the Archive documentation says, or you can get the file by FileId (entered as url parameter) as mentioned in documentation of InvoiceFileConnections.

Now, what is the difference?
When uploading file through Archive or Inbox, you get file entity containing properties "Id" and "ArchiveFileId".

The Archive documentation does not say anything about the "ArchiveFileId" property, neither in response example or property list. Inbox documentation, on the other hand says there is ArchiveId property in the response entity, which corresponds to the Id of the file in Archive. This made sense, but now it seems the functionality has changed but documentation did not.

It seems to me that the Inbox and Archive implementation was united, so both of them now returns the same response entity, including Id and ArchiveFileId properties. The Id represents Id in both Archive and Inbox, and the FileId represents file id in both Archive and Inbox.

I don't get why there are two properties with two different GUIDs now, which makes it very confusing.
Now the problem is, I guess some users use Id and others use ArchiveFileId when creating the file connections.
For now, I can add method DownloadByFileId to the connector as an alternative if Download (by Id) does not work.

**Comment by richardrandak** [comment]
Try calling `await connector.DownloadFileAsync(fileId, IdType.FileId);` in new update [v3.3.3](https://www.nuget.org/packages/Fortnox.NET.SDK/3.3.3 )
Let me know if that works or not.
